# Generated by Django 4.2.20 on 2025-05-09 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FSBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('full_name', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('result', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('olumlu', 'Olumlu'), ('olumsuz', 'Olumsuz'), ('aranmadi', 'Aranmadı')], default='bekliyor', max_length=20, verbose_name='Sonuç')),
                ('link1', models.URLField(blank=True, null=True, verbose_name='Link 1')),
                ('link2', models.URLField(blank=True, null=True, verbose_name='Link 2')),
                ('reminder_status', models.CharField(choices=[('kapali', 'Kapalı'), ('acik', 'Açık')], default='kapali', max_length=10, verbose_name='Hatırlatıcı Durumu')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='Hatırlatıcı Tarihi')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Hatırlatıcı Saati')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Görüşme Notları')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fsbos', to=settings.AUTH_USER_MODEL, verbose_name='Danışman')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fsbos', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'FSBO',
                'verbose_name_plural': "FSBO'lar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FSBOLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='İşlem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('details', models.TextField(blank=True, verbose_name='Detaylar')),
                ('fsbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='fsbo.fsbo', verbose_name='FSBO')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsbo_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'FSBO Log',
                'verbose_name_plural': 'FSBO Logları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
