# Generated by Django 4.2.20 on 2025-06-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsbo',
            name='contact_type',
            field=models.CharField(choices=[('bilgi_alma', 'Bilgi Alma'), ('daire_sunumu', 'Daire Sunumu'), ('sikayet', 'Şikayet')], default='bilgi_alma', max_length=50, verbose_name='İletişim Türü'),
        ),
    ]
