# Generated by Django 4.2.20 on 2025-04-11 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mahalle Adı')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhoods', to=settings.AUTH_USER_MODEL, verbose_name='Bağlı Danışman')),
            ],
            options={
                'verbose_name': 'Mahalle',
                'verbose_name_plural': 'Mahalleler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('full_name', models.CharField(max_length=100, verbose_name='Adı Soyadı')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('apartment', models.CharField(blank=True, max_length=200, verbose_name='Daire Bilgisi')),
                ('meeting_result', models.TextField(blank=True, verbose_name='Görüşme Sonucu')),
                ('meeting_status', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('olumlu', 'Olumlu'), ('olumsuz', 'Olumsuz')], default='bekliyor', max_length=20, verbose_name='Görüşme Durumu')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Danışman')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.neighborhood', verbose_name='Mahalle')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['-created_at'],
            },
        ),
    ]
