# Generated by Django 4.2.20 on 2025-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='callback_date',
            field=models.DateField(blank=True, help_text='Müşteri ile bir sonraki planlanan görüşme tarihi', null=True, verbose_name='Geri Dönüş Tarihi'),
        ),
    ]
