# Generated by Django 4.2.20 on 2025-04-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_callback_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='callback_date',
        ),
        migrations.AddField(
            model_name='customer',
            name='response_date',
            field=models.DateField(blank=True, help_text='Danışmanın müşteriye geri dönüş yaptığı tarih', null=True, verbose_name='Geri Dönüş Tarihi'),
        ),
    ]
