# Generated by Django 4.2.20 on 2025-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_callback_date_customer_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_reason',
            field=models.CharField(blank=True, choices=[('satin_alma', 'Satın Alma'), ('kiralama', 'Kiralama'), ('fiyat_bilgisi', 'Fiyat Bilgisi'), ('genel_bilgi', 'Genel Bilgi')], max_length=50, null=True, verbose_name='Arama Nedeni'),
        ),
        migrations.AddField(
            model_name='customer',
            name='meeting_type',
            field=models.CharField(blank=True, choices=[('bilgi_alma', 'Bilgi Alma'), ('daire_gezdirme', 'Daire Gezdirme')], max_length=50, null=True, verbose_name='Görüşme Türü'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('branda', 'Branda'), ('sahibinden', 'Sahibinden'), ('referans', 'Referans'), ('emlakjet', 'Emlakjet'), ('sosyal_medya', 'Sosyal Medya'), ('diger', 'Diğer')], max_length=50, null=True, verbose_name='Müşteri Kaynağı'),
        ),
    ]
