# Generated by Django 4.2.20 on 2025-05-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_contact_reason_customer_meeting_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_reason',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='meeting_type',
        ),
    ]
