# Generated by Django 4.2.20 on 2025-05-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_customer_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='Bu tarihte sistem otomatik olarak hatırlatma bildirecek', null=True, verbose_name='Hatırlatma Tarihi'),
        ),
        migrations.CreateModel(
            name='CustomerReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField(verbose_name='Hatırlatma Tarihi')),
                ('message', models.TextField(verbose_name='Hatırlatma Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Gönderildi mi?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Hatırlatma',
                'verbose_name_plural': 'Müşteri Hatırlatmaları',
                'ordering': ['-reminder_date'],
            },
        ),
    ]
