# Generated by Django 4.2.20 on 2025-07-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_customer_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('branda', 'Branda'), ('sahibinden', 'Sahibinden'), ('referans', 'Referans'), ('emlakjet', 'Emlakjet'), ('hepsi_emlak', 'Hepsi Emlak'), ('sosyal_medya', 'Sosyal Medya'), ('diger', 'Diğer')], max_length=50, null=True, verbose_name='Müşteri Kaynağı'),
        ),
    ]
