# Generated by Django 4.2.20 on 2025-07-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_propertyimage_is_main_photo'),
        ('customers', '0010_alter_customer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='portfolio.property', verbose_name='İlgilendiği Gayrimenkul'),
        ),
    ]
