# Generated by Django 4.2.20 on 2025-09-20 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0011_customer_property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neighborhood",
            name="consultant",
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="consultants",
            field=models.ManyToManyField(
                blank=True,
                related_name="neighborhoods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bağlı Danışmanlar",
            ),
        ),
    ]
