# Generated by Django 4.2.20 on 2025-09-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0012_remove_neighborhood_consultant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neighborhood",
            name="consultants",
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="neighborhoods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bağlı Danışman",
            ),
        ),
    ]
