# Generated by Django 4.2.20 on 2026-01-09 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_neighborhood_consultants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=255, unique=True, verbose_name='Çağrı ID')),
                ('direction', models.CharField(choices=[('inbound', 'Gelen'), ('outbound', 'Giden'), ('internal', 'İç Arama')], max_length=20, verbose_name='Yön')),
                ('caller', models.CharField(max_length=50, verbose_name='Arayan')),
                ('called', models.CharField(max_length=50, verbose_name='Aranan')),
                ('extension', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dahili')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('duration', models.IntegerField(default=0, verbose_name='Süre (saniye)')),
                ('status', models.CharField(choices=[('ringing', 'Çalıyor'), ('answered', 'Cevaplandı'), ('completed', 'Tamamlandı'), ('missed', 'Cevapsız'), ('busy', 'Meşgul'), ('failed', 'Başarısız')], max_length=20, verbose_name='Durum')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='Kayıt')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Çağrı Kaydı',
                'verbose_name_plural': 'Çağrı Kayıtları',
                'ordering': ['-start_time'],
            },
        ),
    ]
