# Generated by Django 4.2.20 on 2026-01-10 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_calllog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
