# Generated by Django 4.2.20 on 2026-04-13 18:56
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0018_portal_notifications'),
        ('customers', '0015_delete_calllog'),
    ]
    operations = [
        migrations.AddField(
            model_name='customer',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='portfolio.property', verbose_name='İlgilendiği Gayrimenkul'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Bu telefon numarası ile kayıtlı bir müşteri zaten mevcut.'}, max_length=20, unique=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mahalle Adı'),
        ),
    ]