# Generated by Django 4.2.20 on 2026-04-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_remove_customer_property_customer_real_estate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='property',
        ),
    ]
