# Generated by Django 4.2.20 on 2026-04-20 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0018_portal_notifications'),
        ('customers', '0017_remove_customer_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Açık Adres'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('bireysel', 'Bireysel Müşteri'), ('kurumsal', 'Kurumsal Müşteri')], default='bireysel', max_length=20, verbose_name='Müşteri Tipi'),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_permission',
            field=models.BooleanField(default=True, verbose_name='E-posta İzni'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('erkek', 'Erkek'), ('kadin', 'Kadın'), ('belirtilmemis', 'Belirtilmemiş')], default='belirtilmemis', max_length=20, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_permission',
            field=models.BooleanField(default=True, verbose_name='SMS İzni'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('potansiyel', 'Potansiyel'), ('aktif', 'Aktif'), ('pasif', 'Pasif'), ('kapandi', 'Kapandı')], default='potansiyel', max_length=20, verbose_name='Müşteri Durumu'),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_permission',
            field=models.BooleanField(default=True, verbose_name='WhatsApp İzni'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text="Boş bırakılırsa 'Bilinmeyen Müşteri' olarak gösterilir", max_length=100, verbose_name='Adı Soyadı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.neighborhood', verbose_name='Mahalle'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reminder_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hatırlatma Tarihi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='response_date',
            field=models.DateField(blank=True, null=True, verbose_name='Geri Dönüş Tarihi'),
        ),
        migrations.CreateModel(
            name='CustomerWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('workflow_type', models.CharField(choices=[('satis', 'Satış Süreci'), ('kiralama', 'Kiralama Süreci'), ('takip', 'Takip Süreci'), ('gorusme', 'Görüşme Süreci'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='İş Akışı Türü')),
                ('priority', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('tamamlandi', 'Tamamlandı'), ('gecikmis', 'Gecikmiş'), ('arsivlendi', 'Arşivlendi'), ('iptal', 'İptal')], default='aktif', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='customers.customer', verbose_name='Müşteri')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='portfolio.property', verbose_name='İlgili Portföy')),
            ],
            options={
                'verbose_name': 'Müşteri İş Akışı',
                'verbose_name_plural': 'Müşteri İş Akışları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerWhatsappLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('gonderildi', 'İletildi'), ('basarisiz', 'Başarısız'), ('beklemede', 'Beklemede')], default='beklemede', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='customers.customer', verbose_name='Müşteri')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Müşteri WhatsApp',
                'verbose_name_plural': 'Müşteri WhatsApp Kayıtları',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('priority', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('acik', 'Açık'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='acik', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Son Tarih')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customer_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Görevi',
                'verbose_name_plural': 'Müşteri Görevleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('gonderildi', 'İletildi'), ('basarisiz', 'Başarısız'), ('beklemede', 'Beklemede')], default='beklemede', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='customers.customer', verbose_name='Müşteri')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Müşteri SMS',
                'verbose_name_plural': 'Müşteri SMS Kayıtları',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Teklif Başlığı')),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Teklif Fiyatı')),
                ('currency', models.CharField(choices=[('TRY', 'TRY - Türk Lirası'), ('USD', 'USD - Amerikan Doları'), ('EUR', 'EUR - Euro')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('status', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('kabul', 'Kabul Edildi'), ('red', 'Reddedildi'), ('suresi_doldu', 'Süresi Doldu')], default='bekliyor', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notlar / Açıklama')),
                ('matterport_url', models.URLField(blank=True, null=True, verbose_name='Matterport 3D Sanal Tur')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Geçerlilik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Danışman')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='customers.customer', verbose_name='Müşteri')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='portfolio.property', verbose_name='Portföy')),
            ],
            options={
                'verbose_name': 'Müşteri Teklifi',
                'verbose_name_plural': 'Müşteri Teklifleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('note_type', models.CharField(choices=[('not', 'Not'), ('yorum', 'CRM Yorumu'), ('hatirlatici', 'Hatırlatıcı')], default='not', max_length=20, verbose_name='Tür')),
                ('priority', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notes', to='customers.customer', verbose_name='Müşteri')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Müşteri Notu',
                'verbose_name_plural': 'Müşteri Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Aylık Gelir')),
                ('credit_score', models.IntegerField(blank=True, null=True, verbose_name='Kredi Notu')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Minimum Bütçe')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Maksimum Bütçe')),
                ('notes', models.TextField(blank=True, verbose_name='Finansal Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Finansal Bilgi',
                'verbose_name_plural': 'Müşteri Finansal Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='CustomerDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('daire', 'Daire'), ('mustakil', 'Müstakil'), ('dublex', 'Dublex'), ('arsa', 'Arsa'), ('isyeri', 'İşyeri')], max_length=20, verbose_name='Emlak Tipi')),
                ('transaction_type', models.CharField(choices=[('satilik', 'Satılık'), ('kiralik', 'Kiralık')], max_length=20, verbose_name='İşlem Tipi')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Min Fiyat')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Max Fiyat')),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Min m²')),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Max m²')),
                ('room_count', models.CharField(blank=True, max_length=20, verbose_name='Oda Sayısı')),
                ('preferred_locations', models.TextField(blank=True, verbose_name='Tercih Edilen Bölgeler')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('pasif', 'Pasif'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='aktif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Müşteri Talebi',
                'verbose_name_plural': 'Müşteri Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('cagri_gelen', 'Gelen Arama'), ('cagri_giden', 'Giden Arama'), ('sms_gonderildi', 'SMS Gönderildi'), ('whatsapp_gonderildi', 'WhatsApp Gönderildi'), ('teklif_olusturuldu', 'Teklif Oluşturuldu'), ('surec_baslatildi', 'Süreç Başlatıldı'), ('not_eklendi', 'Not Eklendi'), ('gorev_olusturuldu', 'Görev Oluşturuldu'), ('gorev_tamamlandi', 'Görev Tamamlandı'), ('talep_olusturuldu', 'Talep Oluşturuldu'), ('musteri_guncellendi', 'Müşteri Güncellendi'), ('diger', 'Diğer')], max_length=30, verbose_name='Aktivite Türü')),
                ('source_label', models.CharField(blank=True, help_text="Örn: 'Sanal Santral', 'Manuel', 'Sistem'", max_length=50, verbose_name='Kaynak Etiketi')),
                ('description', models.CharField(max_length=500, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer', verbose_name='Müşteri')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Müşteri Aktivitesi',
                'verbose_name_plural': 'Müşteri Aktiviteleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
