# Generated by Django 4.2.20 on 2026-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_customerpresentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerworkflow',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('geri_donus', 'Geri Dönüş'), ('daire_sunumu', 'Daire Sunumu'), ('satis', 'Satış'), ('iptal_olacak', 'İptal Olacak')], default='aktif', max_length=20),
        ),
    ]
