# Generated by Django 4.2.20 on 2025-06-17 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Firma/Kurum')),
                ('subject', models.CharField(choices=[('genel_bilgi', 'Genel Bilgi'), ('gayrimenkul_danisma', 'Gayrimenkul Danışmanlığı'), ('satis', 'Satış'), ('kira', 'Kiralama'), ('değerleme', 'Değerleme'), ('yatirim_danisma', 'Yatırım Danışmanlığı'), ('sikayet', 'Şikayet'), ('oneri', 'Öneri'), ('is_birligi', 'İş Birliği'), ('diger', 'Diğer')], max_length=30, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj İçeriği')),
                ('status', models.CharField(choices=[('yeni', 'Yeni Mesaj'), ('okundu', 'Okundu'), ('cevaplandirildi', 'Cevaplandırıldı'), ('kapatildi', 'Kapatıldı')], default='yeni', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('dusuk', 'Düşük'), ('normal', 'Normal'), ('yuksek', 'Yüksek'), ('acil', 'Acil')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Cevaplama Tarihi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.TextField(blank=True, verbose_name='Tarayıcı Bilgisi')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notları')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_messages', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.EmailField(help_text='Yeni mesajlar bu e-posta adresine gönderilir', max_length=254, verbose_name='Bildirim E-posta')),
                ('auto_reply_enabled', models.BooleanField(default=True, verbose_name='Otomatik Cevap Aktif')),
                ('auto_reply_message', models.TextField(default='Mesajınız için teşekkürler. En kısa sürede size geri dönüş yapacağız.', help_text='Yeni mesaj geldiğinde gönderene otomatik olarak gönderilecek mesaj', verbose_name='Otomatik Cevap Mesajı')),
                ('working_hours_start', models.TimeField(default='09:00', verbose_name='Mesai Başlangıç')),
                ('working_hours_end', models.TimeField(default='18:00', verbose_name='Mesai Bitiş')),
                ('working_days', models.CharField(default='pazartesi-cuma', max_length=20, verbose_name='Çalışma Günleri')),
                ('max_daily_messages_per_email', models.PositiveIntegerField(default=5, help_text='Aynı e-posta adresinden günde en fazla kaç mesaj kabul edilir', verbose_name='Günlük Maksimum Mesaj (E-posta Başına)')),
                ('spam_keywords', models.TextField(blank=True, help_text='Virgülle ayrılmış spam kelimeler listesi', verbose_name='Spam Anahtar Kelimeler')),
            ],
            options={
                'verbose_name': 'İletişim Ayarları',
                'verbose_name_plural': 'İletişim Ayarları',
            },
        ),
        migrations.CreateModel(
            name='ContactReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.TextField(verbose_name='Cevap Mesajı')),
                ('replied_at', models.DateTimeField(auto_now_add=True, verbose_name='Cevap Tarihi')),
                ('is_sent_via_email', models.BooleanField(default=False, verbose_name='E-posta ile gönderildi mi?')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='E-posta Gönderim Tarihi')),
                ('contact_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='contact.contactmessage', verbose_name='Ana Mesaj')),
                ('replied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan')),
            ],
            options={
                'verbose_name': 'İletişim Cevabı',
                'verbose_name_plural': 'İletişim Cevapları',
                'ordering': ['-replied_at'],
            },
        ),
    ]
