# Generated by Django 4.2.20 on 2025-06-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactreply',
            name='contact_message',
        ),
        migrations.RemoveField(
            model_name='contactreply',
            name='replied_by',
        ),
        migrations.DeleteModel(
            name='ContactSettings',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='property_type',
            field=models.CharField(blank=True, choices=[('satilik', 'Satılık'), ('kiralik', 'Kiralık'), ('proje', 'Proje'), ('diger', 'Diğer')], max_length=20, verbose_name='Gayrimenkul Tercihi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('yeni', 'Yeni'), ('okundu', 'Okundu'), ('tamamlandi', 'Tamamlandı')], default='yeni', max_length=20, verbose_name='Durum'),
        ),
        migrations.DeleteModel(
            name='ContactReply',
        ),
    ]
