# Generated by Django 4.2.20 on 2025-05-01 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0006_remove_property_customer_source_and_more'),
        ('customers', '0007_remove_customer_apartment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sunum Başlığı')),
                ('presentation_date', models.DateTimeField(verbose_name='Sunum Tarihi')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Müşteri Telefonu')),
                ('customer_source', models.CharField(blank=True, choices=[('branda', 'Branda'), ('sahibinden', 'Sahibinden'), ('referans', 'Referans'), ('emlakjet', 'Emlakjet'), ('sosyal_medya', 'Sosyal Medya'), ('diger', 'Diğer')], max_length=50, null=True, verbose_name='Müşteri Kaynağı')),
                ('other_properties_notes', models.TextField(blank=True, null=True, verbose_name='Gezdirilen Daireler Notları')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.neighborhood', verbose_name='Mahalle')),
                ('other_property1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shown_in_presentation1', to='portfolio.property', verbose_name='Diğer Gezdirilen Daire 1')),
                ('other_property2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shown_in_presentation2', to='portfolio.property', verbose_name='Diğer Gezdirilen Daire 2')),
                ('other_property3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shown_in_presentation3', to='portfolio.property', verbose_name='Diğer Gezdirilen Daire 3')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to=settings.AUTH_USER_MODEL, verbose_name='Sunan Kişi')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='portfolio.property', verbose_name='Daire')),
            ],
            options={
                'verbose_name': 'Daire Sunumu',
                'verbose_name_plural': 'Daire Sunumları',
                'ordering': ['-presentation_date'],
            },
        ),
        migrations.CreateModel(
            name='PresentationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Çok Kötü'), (2, '2 - Kötü'), (3, '3 - Ortalama'), (4, '4 - İyi'), (5, '5 - Çok İyi')], verbose_name='Değerlendirme')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Yorumlar')),
                ('feedback_date', models.DateTimeField(auto_now_add=True, verbose_name='Değerlendirme Tarihi')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='presentation.presentation', verbose_name='Sunum')),
            ],
            options={
                'verbose_name': 'Sunum Geri Bildirimi',
                'verbose_name_plural': 'Sunum Geri Bildirimleri',
                'ordering': ['-feedback_date'],
            },
        ),
    ]
