# Generated by Django 4.2.20 on 2025-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='other_properties_notes',
        ),
        migrations.AddField(
            model_name='presentation',
            name='property_notes1',
            field=models.TextField(blank=True, null=True, verbose_name='Daire 1 Notları'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='property_notes2',
            field=models.TextField(blank=True, null=True, verbose_name='Daire 2 Notları'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='property_notes3',
            field=models.TextField(blank=True, null=True, verbose_name='Daire 3 Notları'),
        ),
    ]
