# Generated by Django 4.2.20 on 2025-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_remove_presentation_other_properties_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='completion_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Tamamlama Notları'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Sunum Tamamlandı'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='shown_properties',
            field=models.JSONField(blank=True, default=list, verbose_name='Gösterilen Daireler'),
        ),
    ]
