# Generated by Django 4.2.20 on 2025-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0003_presentation_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='presentation_location_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Sunum Konumu Enlem'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='presentation_location_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Sunum Konumu Boylam'),
        ),
    ]
