# Generated by Django 4.2.20 on 2025-08-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0004_add_location_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='presentation_location_lat',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='presentation_location_lng',
        ),
    ]
