# Generated by Django 4.2.20 on 2025-06-18 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ekip üyesinin tam adı', max_length=100, verbose_name='Ad Soyad')),
                ('position', models.CharField(choices=[('ceo', 'CEO & Kurucu'), ('manager', 'Müdür'), ('consultant', 'Gayrimenkul Danışmanı'), ('senior_consultant', 'Kıdemli Gayrimenkul Danışmanı'), ('specialist', 'Uzman'), ('coordinator', 'Koordinatör'), ('assistant', 'Asistan'), ('other', 'Diğer')], help_text='Ekip üyesinin pozisyonu', max_length=50, verbose_name='Pozisyon')),
                ('custom_position', models.CharField(blank=True, help_text='Listede olmayan özel pozisyon girebilirsiniz', max_length=100, null=True, verbose_name='Özel Pozisyon')),
                ('image', models.ImageField(blank=True, help_text='Ekip üyesinin fotoğrafı (önerilen boyut: 250x250px)', null=True, upload_to='team/', verbose_name='Fotoğraf')),
                ('image_url', models.URLField(blank=True, help_text="Harici bir fotoğraf URL'si (fotoğraf yüklenmemişse kullanılır)", null=True, validators=[django.core.validators.URLValidator()], verbose_name='Fotoğraf URL')),
                ('bio', models.TextField(blank=True, help_text='Ekip üyesi hakkında kısa bilgi', null=True, verbose_name='Biyografi')),
                ('email', models.EmailField(blank=True, help_text='Ekip üyesinin e-posta adresi', max_length=254, null=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, help_text='Ekip üyesinin telefon numarası', max_length=20, null=True, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profil bağlantısı', null=True, verbose_name='LinkedIn')),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Sektördeki deneyim yılı', null=True, verbose_name='Deneyim (Yıl)')),
                ('is_active', models.BooleanField(default=True, help_text='Web sitesinde gösterilsin mi?', verbose_name='Aktif')),
                ('is_featured', models.BooleanField(default=False, help_text='Ana sayfada öne çıkarılsın mı?', verbose_name='Öne Çıkan')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Web sitesinde gösterilme sırası (küçük sayı önce gösterilir)', verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
