# Generated by Django 4.2.20 on 2025-04-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar', '0002_alter_event_id_alter_todoitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_todos', to=settings.AUTH_USER_MODEL, verbose_name='Atayan'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_todos', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Danışman'),
        ),
    ]
