# Generated by Django 4.2.20 on 2025-04-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_customer_callback_date_customer_response_date'),
        ('calendar', '0003_todoitem_assigned_by_todoitem_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='address_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adres Detayı'),
        ),
        migrations.AddField(
            model_name='event',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='customers.neighborhood', verbose_name='Mahalle'),
        ),
    ]
