# Generated by Django 4.2.20 on 2025-04-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_remove_event_location_event_address_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address_details',
        ),
        migrations.RemoveField(
            model_name='event',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Konum'),
        ),
    ]
