# Generated by Django 4.2.20 on 2025-12-30 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0013_remove_neighborhood_consultants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(blank=True, help_text="Netgsm'den gelen unique call identifier (eğer varsa)", max_length=100, null=True, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Gelen'), ('outbound', 'Giden')], max_length=10)),
                ('caller', models.CharField(help_text='Arayan numara', max_length=20)),
                ('called', models.CharField(help_text='Aranan numara', max_length=20)),
                ('extension', models.CharField(blank=True, help_text='Dahili numara', max_length=10)),
                ('start_time', models.DateTimeField(help_text='Çağrı başlangıç zamanı')),
                ('end_time', models.DateTimeField(blank=True, help_text='Çağrı bitiş zamanı', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Süre (saniye)', null=True)),
                ('recording_url', models.URLField(blank=True, help_text='Kayıt linki')),
                ('status', models.CharField(blank=True, help_text='Çağrı durumu', max_length=20)),
                ('customer', models.ForeignKey(blank=True, help_text='Telefon numarasına göre eşleştirilen müşteri', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Çağrı Logu',
                'verbose_name_plural': 'Çağrı Logları',
                'ordering': ['-start_time'],
            },
        ),
    ]
