# Generated by Django 4.2.20 on 2026-01-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='called',
            field=models.CharField(help_text='Aranan numara', max_length=100),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='caller',
            field=models.CharField(help_text='Arayan numara', max_length=100),
        ),
    ]
