# Generated by Django 4.2.20 on 2026-01-05 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_neighborhood_consultants_and_more'),
        ('calls', '0002_alter_calllog_called_alter_calllog_caller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='called',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='caller',
        ),
        migrations.AddField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='from_number',
            field=models.CharField(default=2, help_text='Arayan telefon numarası', max_length=100, verbose_name='Arayan Numara'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='to_number',
            field=models.CharField(default='0000000000', help_text='Aranan telefon numarası', max_length=100, verbose_name='Aranan Numara'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_id',
            field=models.CharField(blank=True, help_text="NetGSM'den gelen unique call identifier", max_length=100, null=True, unique=True, verbose_name='Çağrı ID'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Telefon numarasına göre eşleştirilen müşteri', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customers.customer', verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Gelen'), ('outbound', 'Giden')], max_length=10, verbose_name='Yön'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(blank=True, default=0, help_text='Süre (saniye)', null=True, verbose_name='Süre'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Çağrı bitiş zamanı', null=True, verbose_name='Bitiş Zamanı'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='extension',
            field=models.CharField(blank=True, help_text='Dahili numara', max_length=10, verbose_name='Dahili'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='recording_url',
            field=models.URLField(blank=True, help_text="Çağrı kaydı URL'si", verbose_name='Kayıt Linki'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='start_time',
            field=models.DateTimeField(help_text='Çağrı başlangıç zamanı', verbose_name='Başlangıç Zamanı'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(blank=True, choices=[('answered', 'Cevaplandı'), ('missed', 'Cevapsız'), ('busy', 'Meşgul'), ('failed', 'Başarısız')], help_text='Çağrı durumu', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['-start_time'], name='calls_calll_start_t_cc94c4_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['call_id'], name='calls_calll_call_id_b463c5_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['from_number'], name='calls_calll_from_nu_277f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['to_number'], name='calls_calll_to_numb_4e24dd_idx'),
        ),
    ]
