# Generated by Django 4.2.20 on 2026-01-10 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_delete_calllog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0003_remove_calllog_called_remove_calllog_caller_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-start_time'], 'verbose_name': 'Çağrı Kaydı', 'verbose_name_plural': 'Çağrı Kayıtları'},
        ),
        migrations.RemoveIndex(
            model_name='calllog',
            name='calls_calll_start_t_cc94c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='calllog',
            name='calls_calll_call_id_b463c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='calllog',
            name='calls_calll_from_nu_277f1e_idx',
        ),
        migrations.RemoveIndex(
            model_name='calllog',
            name='calls_calll_to_numb_4e24dd_idx',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='from_number',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='to_number',
        ),
        migrations.AddField(
            model_name='calllog',
            name='called',
            field=models.CharField(default='', max_length=50, verbose_name='Aranan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='caller',
            field=models.CharField(default='', max_length=50, verbose_name='Arayan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to=settings.AUTH_USER_MODEL, verbose_name='Personel'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_id',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Çağrı ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calllog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='customers.customer', verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='direction',
            field=models.CharField(choices=[('inbound', 'Gelen'), ('outbound', 'Giden'), ('internal', 'İç Arama')], max_length=20, verbose_name='Yön'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Süre (saniye)'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='extension',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dahili'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='recording_url',
            field=models.URLField(blank=True, null=True, verbose_name='Kayıt'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='start_time',
            field=models.DateTimeField(verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('ringing', 'Çalıyor'), ('answered', 'Cevaplandı'), ('completed', 'Tamamlandı'), ('missed', 'Cevapsız'), ('busy', 'Meşgul'), ('failed', 'Başarısız')], max_length=20, verbose_name='Durum'),
        ),
    ]
