# Generated by Django 4.2.20 on 2026-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_calllog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Dahili'),
        ),
    ]
