# Generated by Django 4.2.20 on 2026-06-28 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calls', '0006_alter_calllog_recording_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Geri Donus Yapildi'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Geri Donus Zamani'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_calls', to=settings.AUTH_USER_MODEL, verbose_name='Geri Donus Yapan'),
        ),
    ]
