# Generated by Django 4.2.20 on 2025-08-20 23:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0011_customer_property'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0014_propertyimage_is_main_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Lead ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('customer_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('source', models.CharField(choices=[('branda', 'Branda'), ('sahibinden', 'Sahibinden'), ('referans', 'Referans'), ('emlakjet', 'Emlakjet'), ('hepsi_emlak', 'Hepsi Emlak'), ('sosyal_medya', 'Sosyal Medya'), ('netgsm_call', 'Santral Çağrısı'), ('whatsapp', 'WhatsApp'), ('diger', 'Diğer')], max_length=50, verbose_name='Kaynak')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Min Bütçe')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Max Bütçe')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('lost', 'Kaybedildi')], default='active', max_length=20, verbose_name='Durum')),
                ('priority', models.PositiveIntegerField(default=3, verbose_name='Öncelik (1-5)')),
                ('contract_signed', models.BooleanField(default=False, verbose_name='Sözleşme İmzalandı')),
                ('contract_date', models.DateTimeField(blank=True, null=True, verbose_name='Sözleşme Tarihi')),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Nakit'), ('credit', 'Kredili')], max_length=20, verbose_name='Ödeme Tipi')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Sözleşme Tutarı')),
                ('deed_transfer_date', models.DateField(blank=True, null=True, verbose_name='Tapu Devir Tarihi')),
                ('deed_completed', models.BooleanField(default=False, verbose_name='Tapu Devri Tamamlandı')),
                ('satisfaction_survey_sent', models.BooleanField(default=False, verbose_name='Memnuniyet Anketi Gönderildi')),
                ('satisfaction_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Memnuniyet Puanı (1-5)')),
                ('satisfaction_feedback', models.TextField(blank=True, verbose_name='Memnuniyet Geri Bildirimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='Son İletişim Tarihi')),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Sonraki Takip Tarihi')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel')),
            ],
            options={
                'verbose_name': 'Satış Potansiyeli',
                'verbose_name_plural': 'Satış Potansiyelleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Aşama Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('stage_type', models.CharField(choices=[('staff', 'Personel Akışı'), ('manager', 'Müdür Akışı')], max_length=20, verbose_name='Akış Tipi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('auto_transition_enabled', models.BooleanField(default=False, verbose_name='Otomatik Geçiş')),
                ('auto_transition_condition', models.CharField(blank=True, max_length=200, verbose_name='Geçiş Koşulu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Satış Aşaması',
                'verbose_name_plural': 'Satış Aşamaları',
                'ordering': ['stage_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True, verbose_name='Mesaj ID')),
                ('direction', models.CharField(choices=[('outbound', 'Giden'), ('inbound', 'Gelen')], max_length=10, verbose_name='Yön')),
                ('message_type', models.CharField(choices=[('text', 'Metin'), ('image', 'Resim'), ('document', 'Belge'), ('template', 'Şablon'), ('interactive', 'Etkileşimli')], max_length=20, verbose_name='Mesaj Tipi')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('media_url', models.URLField(blank=True, verbose_name='Medya URL')),
                ('status', models.CharField(choices=[('sent', 'Gönderildi'), ('delivered', 'Teslim Edildi'), ('read', 'Okundu'), ('failed', 'Başarısız')], default='sent', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('template_name', models.CharField(blank=True, max_length=100, verbose_name='Şablon Adı')),
                ('template_language', models.CharField(default='tr', max_length=10, verbose_name='Şablon Dili')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='sales_process.lead', verbose_name='Lead')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'WhatsApp Mesajı',
                'verbose_name_plural': 'WhatsApp Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('call', 'Arama Yapma'), ('whatsapp', 'WhatsApp Gönderme'), ('email', 'E-posta Gönderme'), ('meeting', 'Randevu Ayarlama'), ('follow_up', 'Takip'), ('deed_transfer', 'Tapu Devri'), ('survey', 'Anket Gönderme'), ('reminder', 'Hatırlatma')], max_length=20, verbose_name='Görev Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Görev Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('priority', models.PositiveIntegerField(choices=[(1, 'Çok Düşük'), (2, 'Düşük'), (3, 'Normal'), (4, 'Yüksek'), (5, 'Çok Yüksek')], default=3, verbose_name='Öncelik')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('overdue', 'Gecikmiş')], default='pending', max_length=20, verbose_name='Durum')),
                ('due_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('is_automatic', models.BooleanField(default=False, verbose_name='Otomatik Görev')),
                ('auto_complete_condition', models.CharField(blank=True, max_length=200, verbose_name='Otomatik Tamamlama Koşulu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='sales_process.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_type', models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Otomatik'), ('webhook', 'Webhook'), ('system', 'Sistem')], max_length=20, verbose_name='Geçiş Tipi')),
                ('reason', models.TextField(blank=True, verbose_name='Geçiş Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Geçiş Tarihi')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transitions_from', to='sales_process.salesstage', verbose_name='Önceki Aşama')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='sales_process.lead', verbose_name='Lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerçekleştiren')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions_to', to='sales_process.salesstage', verbose_name='Sonraki Aşama')),
            ],
            options={
                'verbose_name': 'Aşama Geçişi',
                'verbose_name_plural': 'Aşama Geçişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('call', 'Telefon Görüşmesi'), ('whatsapp', 'WhatsApp Mesajı'), ('meeting', 'Yüz Yüze Görüşme'), ('email', 'E-posta'), ('system', 'Sistem Notu'), ('reminder', 'Hatırlatma')], max_length=20, verbose_name='Not Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('is_important', models.BooleanField(default=False, verbose_name='Önemli')),
                ('contact_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Görüşme Süresi (saniye)')),
                ('contact_successful', models.BooleanField(blank=True, null=True, verbose_name='İletişim Başarılı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sales_process.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead Notu',
                'verbose_name_plural': 'Lead Notları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='current_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales_process.salesstage', verbose_name='Mevcut Aşama'),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='customers.customer', verbose_name='Müşteri'),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='portfolio.property', verbose_name='İlgilenilen Gayrimenkul'),
        ),
        migrations.AddField(
            model_name='lead',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.neighborhood', verbose_name='İlgilenilen Mahalle'),
        ),
        migrations.AddField(
            model_name='lead',
            name='original_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_leads', to=settings.AUTH_USER_MODEL, verbose_name='İlk Atanan Personel'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True, verbose_name='Çağrı ID')),
                ('call_type', models.CharField(choices=[('inbound', 'Gelen'), ('outbound', 'Giden'), ('missed', 'Cevapsız')], max_length=10, verbose_name='Çağrı Tipi')),
                ('caller_number', models.CharField(max_length=20, verbose_name='Arayan Numara')),
                ('called_number', models.CharField(max_length=20, verbose_name='Aranan Numara')),
                ('status', models.CharField(choices=[('answered', 'Cevaplanmış'), ('missed', 'Cevapsız'), ('busy', 'Meşgul'), ('failed', 'Başarısız'), ('no_answer', 'Cevap Yok')], max_length=20, verbose_name='Durum')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Süre (saniye)')),
                ('recording_url', models.URLField(blank=True, verbose_name='Kayıt URL')),
                ('recording_available', models.BooleanField(default=False, verbose_name='Kayıt Mevcut')),
                ('started_at', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_calls', to=settings.AUTH_USER_MODEL, verbose_name='Görüşen Personel')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='sales_process.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Çağrı Kaydı',
                'verbose_name_plural': 'Çağrı Kayıtları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('property_viewing', 'Daire Gezisi'), ('meeting', 'Görüşme'), ('contract_signing', 'Sözleşme İmzalama'), ('deed_transfer', 'Tapu Devri'), ('other', 'Diğer')], max_length=30, verbose_name='Randevu Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Randevu Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('scheduled_date', models.DateTimeField(verbose_name='Randevu Tarihi')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Süre (dakika)')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Konum')),
                ('customer_confirmed', models.BooleanField(default=False, verbose_name='Müşteri Onayı')),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('no_show', 'Gelmedi'), ('rescheduled', 'Ertelendi')], default='scheduled', max_length=20, verbose_name='Durum')),
                ('result_notes', models.TextField(blank=True, verbose_name='Sonuç Notları')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Personel')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='sales_process.lead', verbose_name='Lead')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='portfolio.property', verbose_name='Gayrimenkul')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
