# Generated by Django 4.2.20 on 2025-08-21 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('auto', 'Otomatik'), ('manual', 'Manuel'), ('sticky', 'Sticky Assignment'), ('geographic', 'Coğrafi'), ('workload', 'İş Yükü'), ('round_robin', 'Sıralı')], max_length=20, verbose_name='Atama Tipi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('reassigned', 'Yeniden Atandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='active', max_length=20, verbose_name='Durum')),
                ('is_sticky', models.BooleanField(default=False, verbose_name='Sticky Assignment')),
                ('sticky_reason', models.CharField(blank=True, max_length=200, verbose_name='Sticky Nedeni')),
                ('assignment_reason', models.TextField(blank=True, verbose_name='Atama Nedeni')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atama Tarihi')),
                ('reassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Yeniden Atama Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('workload_score', models.FloatField(blank=True, null=True, verbose_name='İş Yükü Skoru')),
                ('geographic_match', models.BooleanField(default=False, verbose_name='Coğrafi Eşleşme')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atayan Kişi')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='sales_process.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Lead Ataması',
                'verbose_name_plural': 'Lead Atamaları',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['lead', 'status'], name='sales_proce_lead_id_4d136b_idx'), models.Index(fields=['assigned_to', 'status'], name='sales_proce_assigne_2191cf_idx'), models.Index(fields=['is_sticky'], name='sales_proce_is_stic_e31095_idx')],
            },
        ),
    ]
