# Generated by Django 4.2.20 on 2025-08-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0002_leadassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, choices=[('apartment', 'Daire'), ('villa', 'Villa'), ('office', 'Ofis'), ('shop', 'Dükkan'), ('land', 'Arsa'), ('other', 'Diğer')], max_length=20, verbose_name='Gayrimenkul Tipi'),
        ),
    ]
