# Generated by Django 4.2.20 on 2025-08-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0003_lead_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Gayrimenkul Lokasyonu'),
        ),
    ]
