# Generated by Django 4.2.20 on 2025-08-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0004_lead_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='stage_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aşama Güncelleme Tarihi'),
        ),
    ]
