# Generated by Django 4.2.20 on 2025-08-21 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_propertyimage_is_main_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_process', '0005_lead_stage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Sözleşme Numarası')),
                ('contract_date', models.DateTimeField(verbose_name='Sözleşme Tarihi')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sözleşme Tutarı')),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Peşinat')),
                ('payment_type', models.CharField(choices=[('cash', 'Nakit'), ('credit', 'Kredili'), ('installment', 'Taksitli'), ('mixed', 'Karma')], max_length=20, verbose_name='Ödeme Tipi')),
                ('installment_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taksit Sayısı')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aylık Ödeme')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banka Adı')),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kredi Tutarı')),
                ('loan_approved', models.BooleanField(blank=True, null=True, verbose_name='Kredi Onayı')),
                ('loan_approval_date', models.DateField(blank=True, null=True, verbose_name='Kredi Onay Tarihi')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('signed', 'İmzalandı'), ('cancelled', 'İptal'), ('expired', 'Süresi Doldu')], default='draft', max_length=20, verbose_name='Durum')),
                ('signed_date', models.DateTimeField(blank=True, null=True, verbose_name='İmza Tarihi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Son Geçerlilik Tarihi')),
                ('contract_document_url', models.URLField(blank=True, verbose_name='Sözleşme Belgesi URL')),
                ('signed_document_url', models.URLField(blank=True, verbose_name='İmzalı Belge URL')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='İptal Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='sales_process.lead', verbose_name='Lead')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Hazırlayan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='portfolio.property', verbose_name='Gayrimenkul')),
            ],
            options={
                'verbose_name': 'Sözleşme',
                'verbose_name_plural': 'Sözleşmeler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CALL_OK', 'Arama Başarılı'), ('CALL_FAIL', 'Arama Başarısız'), ('OFFER_SENT', 'Teklif Gönderildi'), ('APPT_SET', 'Randevu Ayarlandı'), ('SHOW_DONE', 'Sunum Tamamlandı'), ('CONTRACT_CREATED', 'Sözleşme Oluşturuldu'), ('CONTRACT_DECLINED', 'Sözleşme Reddedildi'), ('CONTRACT_PAYMENT_SELECTED', 'Ödeme Tipi Seçildi'), ('TITLE_DEED_DONE', 'Tapu Devri Tamamlandı'), ('WHATSAPP_OUT', 'WhatsApp Gönderildi'), ('WHATSAPP_IN', 'WhatsApp Geldi'), ('REVIEW_RECEIVED', 'Yorum Alındı'), ('STAGE_CHANGED', 'Aşama Değişti'), ('TASK_CREATED', 'Görev Oluşturuldu'), ('TASK_COMPLETED', 'Görev Tamamlandı'), ('SYSTEM', 'Sistem Aksiyonu')], max_length=30, verbose_name='Aksiyon Tipi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Ek Veriler')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Başarılı')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aksiyon Tarihi')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='sales_process.lead', verbose_name='Lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gerçekleştiren')),
                ('related_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='sales_process.appointment', verbose_name='İlgili Randevu')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='sales_process.task', verbose_name='İlgili Görev')),
            ],
            options={
                'verbose_name': 'Aksiyon Logu',
                'verbose_name_plural': 'Aksiyon Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyShown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gösterim Tarihi')),
                ('customer_interest_level', models.PositiveIntegerField(blank=True, choices=[(1, 'Çok Düşük'), (2, 'Düşük'), (3, 'Orta'), (4, 'Yüksek'), (5, 'Çok Yüksek')], null=True, verbose_name='Müşteri İlgi Düzeyi')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Müşteri Notları')),
                ('staff_notes', models.TextField(blank=True, verbose_name='Personel Notları')),
                ('visit_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ziyaret Süresi (dakika)')),
                ('questions_asked', models.TextField(blank=True, verbose_name='Sorulan Sorular')),
                ('objections_raised', models.TextField(blank=True, verbose_name='İtirazlar')),
                ('is_interested', models.BooleanField(blank=True, null=True, verbose_name='İlgilendiği Onaylandı')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Takip Gerekli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_properties', to='sales_process.lead', verbose_name='Lead')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showings', to='portfolio.property', verbose_name='Gayrimenkul')),
                ('shown_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_showings', to=settings.AUTH_USER_MODEL, verbose_name='Gösteren Personel')),
            ],
            options={
                'verbose_name': 'Gösterilen Gayrimenkul',
                'verbose_name_plural': 'Gösterilen Gayrimenkuller',
                'ordering': ['-shown_date'],
                'unique_together': {('lead', 'property', 'shown_date')},
            },
        ),
    ]
