# Generated by Django 4.2.20 on 2025-08-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0006_contract_actionlog_propertyshown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='propertyshown',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='propertyshown',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='propertyshown',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyshown',
            name='shown_by',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('CALL_OK', 'Arama Başarılı'), ('CALL_FAIL', 'Arama Başarısız'), ('OFFER_SENT', 'Teklif Gönderildi'), ('APPT_SET', 'Randevu Ayarlandı'), ('SHOW_DONE', 'Sunum Tamamlandı'), ('CONTRACT_CREATED', 'Sözleşme Oluşturuldu'), ('CONTRACT_SIGNED', 'Sözleşme İmzalandı'), ('PAYMENT_RECEIVED', 'Ödeme Alındı'), ('DEED_TRANSFER', 'Tapu Devri'), ('SURVEY_SENT', 'Anket Gönderildi'), ('STAGE_CHANGED', 'Aşama Değişti'), ('NOTE_ADDED', 'Not Eklendi'), ('TASK_CREATED', 'Görev Oluşturuldu'), ('TASK_COMPLETED', 'Görev Tamamlandı'), ('WHATSAPP_SENT', 'WhatsApp Gönderildi'), ('EMAIL_SENT', 'E-posta Gönderildi'), ('DOCUMENT_UPLOADED', 'Belge Yüklendi'), ('PROPERTY_SHOWN', 'Gayrimenkul Gösterildi'), ('FOLLOW_UP', 'Takip Yapıldı'), ('LEAD_CREATED', 'Lead Oluşturuldu'), ('LEAD_ASSIGNED', 'Lead Atandı'), ('CUSTOMER_RESPONSE', 'Müşteri Yanıtı'), ('SYSTEM_ACTION', 'Sistem Aksiyonu')], max_length=20, verbose_name='Aksiyon Tipi'),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='note_type',
            field=models.CharField(choices=[('call', 'Telefon Görüşmesi'), ('whatsapp', 'WhatsApp Mesajı'), ('meeting', 'Yüz Yüze Görüşme'), ('email', 'E-posta'), ('system', 'Sistem Notu'), ('reminder', 'Hatırlatma'), ('error', 'Hata')], max_length=20, verbose_name='Not Tipi'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Metin'), ('image', 'Resim'), ('document', 'Belge'), ('template', 'Şablon'), ('interactive', 'Etkileşimli'), ('offer_sent', 'Teklif Gönderildi')], max_length=20, verbose_name='Mesaj Tipi'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['lead', 'action_type'], name='sales_proce_lead_id_3ea92e_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['performed_by', 'created_at'], name='sales_proce_perform_23d5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='actionlog',
            index=models.Index(fields=['is_successful'], name='sales_proce_is_succ_04e78a_idx'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='PropertyShown',
        ),
    ]
