# Generated by Django 4.2.20 on 2025-08-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0007_remove_contract_lead_remove_contract_prepared_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('CALL_OK', 'Arama Başarılı'), ('CALL_FAIL', 'Arama Başarısız'), ('OFFER_SENT', 'Teklif Gönderildi'), ('OFFER_ACCEPTED', 'Teklif Kabul Edildi'), ('OFFER_REJECTED', 'Teklif Reddedildi'), ('APPT_SET', 'Randevu Ayarlandı'), ('SHOW_DONE', 'Sunum Tamamlandı'), ('CONTRACT_CREATED', 'Sözleşme Oluşturuldu'), ('CONTRACT_SIGNED', 'Sözleşme İmzalandı'), ('PAYMENT_RECEIVED', 'Ödeme Alındı'), ('DEED_TRANSFER', 'Tapu Devri'), ('SURVEY_SENT', 'Anket Gönderildi'), ('STAGE_CHANGED', 'Aşama Değişti'), ('NOTE_ADDED', 'Not Eklendi'), ('TASK_CREATED', 'Görev Oluşturuldu'), ('TASK_COMPLETED', 'Görev Tamamlandı'), ('WHATSAPP_SENT', 'WhatsApp Gönderildi'), ('EMAIL_SENT', 'E-posta Gönderildi'), ('DOCUMENT_UPLOADED', 'Belge Yüklendi'), ('PROPERTY_SHOWN', 'Gayrimenkul Gösterildi'), ('FOLLOW_UP', 'Takip Yapıldı'), ('LEAD_CREATED', 'Lead Oluşturuldu'), ('LEAD_ASSIGNED', 'Lead Atandı'), ('CUSTOMER_RESPONSE', 'Müşteri Yanıtı'), ('SYSTEM_ACTION', 'Sistem Aksiyonu')], max_length=20, verbose_name='Aksiyon Tipi'),
        ),
    ]
