# Generated by Django 4.2.20 on 2025-08-24 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_process', '0008_alter_actionlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kapatılma Tarihi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_leads', to=settings.AUTH_USER_MODEL, verbose_name='Kapatan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Dosya Kapatıldı'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('CALL_OK', 'Arama Başarılı'), ('CALL_FAIL', 'Arama Başarısız'), ('OFFER_SENT', 'Teklif Gönderildi'), ('OFFER_ACCEPTED', 'Teklif Kabul Edildi'), ('OFFER_REJECTED', 'Teklif Reddedildi'), ('APPT_SET', 'Randevu Ayarlandı'), ('SHOW_DONE', 'Sunum Tamamlandı'), ('CONTRACT_CREATED', 'Sözleşme Oluşturuldu'), ('CONTRACT_SIGNED', 'Sözleşme İmzalandı'), ('PAYMENT_RECEIVED', 'Ödeme Alındı'), ('DEED_TRANSFER', 'Tapu Devri'), ('SURVEY_SENT', 'Anket Gönderildi'), ('FEEDBACK_SENT', 'Memnuniyet Anketi Gönderildi'), ('CASE_CLOSED', 'Dosya Kapatıldı'), ('STAGE_CHANGED', 'Aşama Değişti'), ('NOTE_ADDED', 'Not Eklendi'), ('TASK_CREATED', 'Görev Oluşturuldu'), ('TASK_COMPLETED', 'Görev Tamamlandı'), ('WHATSAPP_SENT', 'WhatsApp Gönderildi'), ('EMAIL_SENT', 'E-posta Gönderildi'), ('DOCUMENT_UPLOADED', 'Belge Yüklendi'), ('PROPERTY_SHOWN', 'Gayrimenkul Gösterildi'), ('FOLLOW_UP', 'Takip Yapıldı'), ('LEAD_CREATED', 'Lead Oluşturuldu'), ('LEAD_ASSIGNED', 'Lead Atandı'), ('CUSTOMER_RESPONSE', 'Müşteri Yanıtı'), ('SYSTEM_ACTION', 'Sistem Aksiyonu')], max_length=20, verbose_name='Aksiyon Tipi'),
        ),
    ]
