# Generated by Django 4.2.20 on 2025-08-24 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales_process', '0009_lead_closed_at_lead_closed_by_lead_is_closed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Boylam')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Doğruluk (metre)')),
                ('location_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Konum Zaman Damgası')),
                ('manual_location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Manuel Konum')),
                ('completion_notes', models.TextField(verbose_name='Sunum Notları')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tamamlanma Tarihi')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tamamlayan')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_locations', to='sales_process.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Sunum Konumu',
                'verbose_name_plural': 'Sunum Konumları',
                'ordering': ['-completed_at'],
            },
        ),
    ]
