# Generated by Django 4.2.20 on 2025-08-24 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0010_presentationlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Anket ID')),
                ('survey_type', models.CharField(choices=[('satisfaction', 'Memnuniyet Anketi'), ('feedback', 'Geri Bildirim'), ('service_quality', 'Hizmet Kalitesi')], default='satisfaction', max_length=20, verbose_name='Anket Tipi')),
                ('access_token', models.CharField(max_length=64, unique=True, verbose_name='Erişim Token')),
                ('status', models.CharField(choices=[('created', 'Oluşturuldu'), ('sent', 'Gönderildi'), ('completed', 'Tamamlandı'), ('expired', 'Süresi Doldu')], default='created', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('expires_at', models.DateTimeField(verbose_name='Son Geçerlilik Tarihi')),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp Mesaj ID')),
                ('whatsapp_sent', models.BooleanField(default=False, verbose_name='WhatsApp Gönderildi')),
                ('overall_satisfaction', models.PositiveIntegerField(blank=True, null=True, verbose_name='Genel Memnuniyet (1-5)')),
                ('service_quality_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hizmet Kalitesi (1-5)')),
                ('staff_performance_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Personel Performansı (1-5)')),
                ('communication_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='İletişim (1-5)')),
                ('process_speed_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='İşlem Hızı (1-5)')),
                ('positive_feedback', models.TextField(blank=True, verbose_name='Olumlu Geri Bildirim')),
                ('improvement_suggestions', models.TextField(blank=True, verbose_name='İyileştirme Önerileri')),
                ('additional_comments', models.TextField(blank=True, verbose_name='Ek Yorumlar')),
                ('would_recommend', models.BooleanField(blank=True, null=True, verbose_name='Tavsiye Eder misiniz?')),
                ('referral_likelihood', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tavsiye Etme Olasılığı (1-10)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Görüntülenme')),
                ('completion_time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamamlanma Süresi (saniye)')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='sales_process.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100, verbose_name='Soru Anahtarı')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('answer_value', models.TextField(verbose_name='Yanıt Değeri')),
                ('answer_type', models.CharField(max_length=20, verbose_name='Yanıt Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yanıtlanma Tarihi')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sales_process.survey', verbose_name='Anket')),
            ],
            options={
                'verbose_name': 'Anket Yanıtı',
                'verbose_name_plural': 'Anket Yanıtları',
                'ordering': ['-created_at'],
                'unique_together': {('survey', 'question_key')},
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['access_token'], name='sales_proce_access__5a45fc_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['lead', 'status'], name='sales_proce_lead_id_d43146_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status', 'expires_at'], name='sales_proce_status_d82ce5_idx'),
        ),
    ]
