# Generated by Django 4.2.20 on 2025-08-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0011_survey_surveyresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_type',
            field=models.CharField(choices=[('bilgi_alma', 'Bilgi Alma'), ('daire_sunumu', 'Daire Sunumu'), ('sikayet', 'Şikayet')], default='bilgi_alma', max_length=50, verbose_name='İletişim Türü'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_result',
            field=models.TextField(blank=True, verbose_name='Görüşme Sonucu'),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_status',
            field=models.CharField(choices=[('bekliyor', 'Bekliyor'), ('olumlu', 'Olumlu'), ('olumsuz', 'Olumsuz')], default='bekliyor', max_length=20, verbose_name='Görüşme Durumu'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='Bu tarihte sistem otomatik olarak hatırlatma bildirecek', null=True, verbose_name='Hatırlatma Tarihi'),
        ),
        migrations.AddField(
            model_name='lead',
            name='response_date',
            field=models.DateField(blank=True, help_text='Danışmanın müşteriye geri dönüş yaptığı tarih', null=True, verbose_name='Geri Dönüş Tarihi'),
        ),
    ]
