# Generated by Django 4.2.20 on 2025-08-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_process', '0012_lead_contact_type_lead_lead_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='customer_email',
        ),
    ]
