# Generated by Django 4.2.20 on 2026-04-29 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saha', '0003_parselkayit_durum_alanlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gunlukgorev',
            options={'ordering': ['tarih'], 'verbose_name': 'Gunluk Gorev', 'verbose_name_plural': 'Gunluk Gorevler'},
        ),
        migrations.AlterModelOptions(
            name='parselkayit',
            options={'ordering': ['-olusturma_tarihi'], 'verbose_name': 'Parsel Kaydi', 'verbose_name_plural': 'Parsel Kayitlari'},
        ),
        migrations.AlterModelOptions(
            name='sahagorevplani',
            options={'ordering': ['-olusturma_tarihi'], 'verbose_name': 'Saha Gorev Plani', 'verbose_name_plural': 'Saha Gorev Planlari'},
        ),
        migrations.AlterModelOptions(
            name='sahagorusme',
            options={'ordering': ['-tarih'], 'verbose_name': 'Saha Gorusmesi', 'verbose_name_plural': 'Saha Gorusmeleri'},
        ),
        migrations.RemoveConstraint(
            model_name='gunlukgorev',
            name='unique_gorev_per_plan_tarih',
        ),
        migrations.RemoveConstraint(
            model_name='sahagorevplani',
            name='unique_plan_per_mahalle_uzman_ay',
        ),
        migrations.AlterField(
            model_name='brokerbildirim',
            name='alici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_bildirimleri', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brokerbildirim',
            name='gorev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bildirimler', to='saha.gunlukgorev'),
        ),
        migrations.AlterField(
            model_name='brokerbildirim',
            name='goruldu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brokerbildirim',
            name='mesaj',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='brokerbildirim',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gunlukgorev',
            name='atanan_parseller',
            field=models.ManyToManyField(blank=True, related_name='gunluk_gorevler', to='saha.parselkayit'),
        ),
        migrations.AlterField(
            model_name='gunlukgorev',
            name='broker_bildirildi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gunlukgorev',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_gorevler', to='saha.sahagorevplani'),
        ),
        migrations.AlterField(
            model_name='gunlukgorev',
            name='tamamlandi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gunlukgorev',
            name='tarih',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='adres',
            field=models.CharField(blank=True, max_length=500, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='diger_not',
            field=models.TextField(blank=True, verbose_name='Bina Hakkinda Notlar'),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='kapici_ad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Kapici Adi'),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='kapici_tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='Kapici Telefonu'),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='mahalle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mahalle'),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parsel_kayitlar', to=settings.AUTH_USER_MODEL, verbose_name='Olusturan'),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='yonetici_ad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Bina Yoneticisi Adi'),
        ),
        migrations.AlterField(
            model_name='parselkayit',
            name='yonetici_tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='Yonetici Telefonu'),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='atayan_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atadigi_planlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='ay',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ocak'), (2, 'Subat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayis'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Agustos'), (9, 'Eylul'), (10, 'Ekim'), (11, 'Kasim'), (12, 'Aralik')]),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='bolge_uzmani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_planlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='calisma_gunu',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='gunluk_hedef',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='mahalle_adi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='toplam_bina',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sahagorevplani',
            name='yil',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sahagorusme',
            name='not_metni',
            field=models.TextField(verbose_name='Gorusme Notu'),
        ),
        migrations.AlterField(
            model_name='sahagorusme',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Gorusme Tarihi'),
        ),
        migrations.AlterUniqueTogether(
            name='gunlukgorev',
            unique_together={('plan', 'tarih')},
        ),
        migrations.AlterUniqueTogether(
            name='sahagorevplani',
            unique_together={('mahalle_adi', 'bolge_uzmani', 'yil', 'ay')},
        ),
    ]
