# Generated by Django 4.2.20 on 2025-04-11 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İlan Başlığı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('property_type', models.CharField(choices=[('daire', 'Daire'), ('arsa', 'Arsa'), ('isyeri', 'İşyeri')], max_length=20, verbose_name='Emlak Tipi')),
                ('status', models.CharField(choices=[('satilik', 'Satılık'), ('kiralik', 'Kiralık')], max_length=20, verbose_name='Durum')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Fiyat')),
                ('address', models.TextField(blank=True, verbose_name='Açık Adres')),
                ('gross_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Brüt m²')),
                ('net_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Net m²')),
                ('room_count', models.CharField(blank=True, max_length=20, verbose_name='Oda Sayısı')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Bulunduğu Kat')),
                ('building_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bina Yaşı')),
                ('heating', models.CharField(blank=True, choices=[('dogalgaz', 'Doğalgaz'), ('merkezi', 'Merkezi Sistem'), ('klima', 'Klima'), ('soba', 'Soba'), ('yok', 'Isıtma Yok')], max_length=20, verbose_name='Isıtma')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balkon')),
                ('dues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aidat')),
                ('deed_status', models.CharField(blank=True, choices=[('kat_mulkiyetli', 'Kat Mülkiyetli'), ('kat_irtifakli', 'Kat İrtifaklı'), ('arsa', 'Arsa'), ('diger', 'Diğer')], max_length=20, verbose_name='Tapu Durumu')),
                ('is_suitable_for_credit', models.BooleanField(default=True, verbose_name='Krediye Uygunluk')),
                ('is_bargainable', models.BooleanField(default=True, verbose_name='Pazarlık Payı')),
                ('owner_name', models.CharField(blank=True, max_length=100, verbose_name='Mal Sahibi')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='Mal Sahibi Telefon')),
                ('owner_listing_number', models.CharField(blank=True, max_length=50, verbose_name='Sahibinden İlan No')),
                ('branda_number', models.CharField(blank=True, max_length=50, verbose_name='Branda No')),
                ('key_holder', models.CharField(blank=True, choices=[('sahibi', 'Ev Sahibi'), ('danisman', 'Emlak Danışmanı'), ('kiracı', 'Kiracı'), ('diger', 'Diğer')], max_length=20, verbose_name='Anahtar Kimde')),
                ('photo_status', models.BooleanField(default=False, verbose_name='Fotoğraf Çekildi')),
                ('listing_date', models.DateField(default=django.utils.timezone.now, verbose_name='İlan Tarihi')),
                ('swot_analysis', models.TextField(blank=True, verbose_name='SWOT Analizi')),
                ('target_audience', models.CharField(blank=True, max_length=100, verbose_name='Hedef Kitle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Danışman')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.neighborhood', verbose_name='Mahalle')),
            ],
            options={
                'verbose_name': 'Portföy',
                'verbose_name_plural': 'Portföyler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Görsel')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Görsel Başlığı')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Sıralama')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.property')),
            ],
            options={
                'verbose_name': 'Gayrimenkul Görseli',
                'verbose_name_plural': 'Gayrimenkul Görselleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100, verbose_name='Yer Adı')),
                ('distance', models.CharField(max_length=20, verbose_name='Uzaklık')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='portfolio.property')),
            ],
            options={
                'verbose_name': 'Çevre Bilgisi',
                'verbose_name_plural': 'Çevre Bilgileri',
            },
        ),
    ]
