# Generated by Django 4.2.20 on 2025-04-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_property_id_alter_propertyenvironment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='banner_status',
            field=models.CharField(blank=True, choices=[('asildi', 'Asıldı'), ('asilmadi', 'Asılmadı')], max_length=20, verbose_name='Branda Durumu'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Banyo Sayısı'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, choices=[('konut', 'Konut'), ('ticari', 'Ticari'), ('arsa', 'Arsa'), ('otel', 'Otel'), ('diger', 'Diğer')], max_length=20, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='property',
            name='customer_source',
            field=models.CharField(blank=True, choices=[('internet', 'İnternet'), ('referans', 'Referans'), ('tabela', 'Tabela/Branda'), ('sosyal_medya', 'Sosyal Medya'), ('diger', 'Diğer')], max_length=20, verbose_name='Müşteri Geliş Kaynağı'),
        ),
        migrations.AddField(
            model_name='property',
            name='customer_tag',
            field=models.CharField(blank=True, choices=[('vip', 'VIP'), ('standart', 'Standart'), ('ozel', 'Özel')], max_length=20, verbose_name='Müşteri Etiketi'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Kat Sayısı'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_exchangeable',
            field=models.BooleanField(default=False, verbose_name='Takas'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_furnished',
            field=models.BooleanField(default=False, verbose_name='Eşyalı'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_in_site',
            field=models.BooleanField(default=False, verbose_name='Site İçerisinde'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_from',
            field=models.CharField(blank=True, choices=[('sahibinden', 'Sahibinden'), ('emlakci', 'Emlakçı'), ('banka', 'Banka'), ('muteahhit', 'Müteahhit')], max_length=20, verbose_name='Kimden'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('acil', 'Acil'), ('firsat', 'Fırsat'), ('yeni', 'Yeni'), ('ozel', 'Özel'), ('normal', 'Normal')], max_length=20, verbose_name='İlan Türü'),
        ),
        migrations.AddField(
            model_name='property',
            name='poster_status',
            field=models.CharField(blank=True, choices=[('asildi', 'Asıldı'), ('asilmadi', 'Asılmadı')], max_length=20, verbose_name='Afiş Durumu'),
        ),
        migrations.AddField(
            model_name='property',
            name='usage_status',
            field=models.CharField(blank=True, choices=[('mulk_sahibi', 'Mülk Sahibi'), ('kiracili', 'Kiracılı'), ('bos', 'Boş')], max_length=20, verbose_name='Kullanım Durumu'),
        ),
    ]
