# Generated by Django 4.2.20 on 2025-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_property_banner_status_property_bathroom_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_status',
            field=models.CharField(blank=True, choices=[('cekildi', 'Çekildi'), ('cektirmiyor', 'Çektirmiyor'), ('cekilmedi', 'Çekilmedi'), ('cekilmiyor', 'Çekilmiyor')], default='cekilmedi', max_length=20, verbose_name='Fotoğraf Durumu'),
        ),
    ]
