# Generated by Django 4.2.20 on 2025-05-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_propertyimage_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='customer_source',
        ),
        migrations.RemoveField(
            model_name='property',
            name='customer_tag',
        ),
        migrations.RemoveField(
            model_name='property',
            name='listing_from',
        ),
        migrations.RemoveField(
            model_name='property',
            name='poster_status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='swot_analysis',
        ),
        migrations.RemoveField(
            model_name='property',
            name='target_audience',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='property',
            name='apartment_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Daire Adı'),
        ),
        migrations.AddField(
            model_name='property',
            name='emlakjet_listing_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Emlakjet İlan No'),
        ),
        migrations.AddField(
            model_name='property',
            name='hepsiemlak_listing_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Hepsiemlak İlan No'),
        ),
        migrations.AddField(
            model_name='property',
            name='map_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Harita Koordinatları'),
        ),
        migrations.AddField(
            model_name='property',
            name='website_listing_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Web Sitesi İlan No'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Detay'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('daire', 'Daire'), ('mustakil', 'Müstakil'), ('dublex', 'Dublex'), ('arsa', 'Arsa'), ('isyeri', 'İşyeri')], max_length=20, verbose_name='Emlak Tipi'),
        ),
    ]
