# Generated by Django 4.2.20 on 2025-05-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_property_customer_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan'),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating',
            field=models.CharField(blank=True, choices=[('dogalgaz', 'Doğalgaz'), ('merkezi', 'Merkezi Sistem'), ('klima', 'Klima'), ('soba', 'Soba'), ('yerden', 'Yerden Isıtma'), ('yok', 'Isıtma Yok')], max_length=20, verbose_name='Isıtma'),
        ),
    ]
