# Generated by Django 4.2.20 on 2025-05-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_property_is_featured_alter_property_heating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_featured',
        ),
    ]
