# Generated by Django 4.2.20 on 2025-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_property_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Kat Sayısı'),
        ),
    ]
