# Generated by Django 4.2.20 on 2025-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_property_floor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan'),
        ),
    ]
