# Generated by Django 4.2.20 on 2025-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_property_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='web_title',
            field=models.CharField(blank=True, help_text='Web sitesinde görünecek ilan başlığı (boş bırakılırsa daire adı kullanılır)', max_length=250, verbose_name='Web Sitesi İlan Başlığı'),
        ),
    ]
