# Generated by Django 4.2.20 on 2025-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_property_web_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/', verbose_name='Küçük Resim'),
        ),
    ]
