# Generated by Django 4.2.20 on 2025-06-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_propertyimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='website_listing_number',
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/', verbose_name='Küçük Görsel'),
        ),
    ]
