# Generated by Django 4.2.20 on 2025-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_remove_property_website_listing_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='is_main_photo',
            field=models.BooleanField(default=False, verbose_name='Ana Fotoğraf'),
        ),
    ]
