# Generated by Django 4.2.20 on 2026-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_propertyimage_is_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='emlakjet_listing_number',
            field=models.CharField(blank=True, max_length=500, verbose_name='Emlakjet İlan No'),
        ),
        migrations.AlterField(
            model_name='property',
            name='hepsiemlak_listing_number',
            field=models.CharField(blank=True, max_length=500, verbose_name='Hepsiemlak İlan No'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_listing_number',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sahibinden İlan No'),
        ),
    ]
