# Generated by Django 4.2.20 on 2026-02-22 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0015_alter_property_emlakjet_listing_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='portfolio.property', verbose_name='Gayrimenkul')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Gayrimenkul Notu',
                'verbose_name_plural': 'Gayrimenkul Notları',
                'ordering': ['-created_at'],
            },
        ),
    ]
