# Generated by Django 4.2.20 on 2026-02-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_propertynote'),
    ]

    operations = [
    ]
