# Generated by Django 4.2.20 on 2026-04-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_portal_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertynote',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Tamamlandi mi?'),
        ),
        migrations.AddField(
            model_name='propertynote',
            name='is_reminder',
            field=models.BooleanField(default=False, verbose_name='Hatirlatma mi?'),
        ),
        migrations.AddField(
            model_name='propertynote',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('onemli', 'Onemli'), ('acil', 'Acil')], default='normal', max_length=10, verbose_name='Oncelik'),
        ),
        migrations.AddField(
            model_name='propertynote',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hatirlatma Tarihi'),
        ),
    ]
