# Generated by Django 4.2.20 on 2026-04-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_property_emlakjet_hepsiemlak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyPriceHistory',
        ),
    ]
