# Generated by Django 4.2.20 on 2026-07-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_add_yetki_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='front',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cephe'),
        ),
    ]
