# Generated by Django 4.2.20 on 2026-07-02 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0026_property_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Kuyrukta'), ('processing', 'İşleniyor'), ('completed', 'Hazır'), ('error', 'Hata')], default='queued', max_length=20, verbose_name='Durum')),
                ('resolution', models.CharField(choices=[('480p', 'Standart (480p)'), ('720p', 'HD (720p)'), ('1080p', 'Sinematik (1080p)')], default='720p', max_length=10, verbose_name='Çözünürlük')),
                ('aspect_ratio', models.CharField(choices=[('9:16', 'Dikey 9:16 — Reels/Story'), ('16:9', 'Yatay 16:9 — YouTube/Web')], default='9:16', max_length=10, verbose_name='En-Boy Oranı')),
                ('photo_order', models.JSONField(default=list, verbose_name='Fotoğraf Sırası (ID listesi)')),
                ('output_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='portfolio.property', verbose_name='Gayrimenkul')),
            ],
            options={
                'verbose_name': 'Video Görevi',
                'verbose_name_plural': 'Video Görevleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
