# Generated by Django 4.2.20 on 2025-06-14 09:30

import apps.careers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('position', models.CharField(choices=[('emlak_danisman', 'Emlak Danışmanı'), ('satis_temsilci', 'Satış Temsilcisi'), ('ofis_eleman', 'Ofis Elemanı'), ('muhasebe', 'Muhasebe Elemanı'), ('pazarlama', 'Pazarlama Uzmanı'), ('insan_kaynaklari', 'İnsan Kaynakları'), ('teknik_destek', 'Teknik Destek'), ('diger', 'Diğer')], max_length=30, verbose_name='Başvurulan Pozisyon')),
                ('experience', models.CharField(choices=[('0-1', '0-1 Yıl'), ('1-3', '1-3 Yıl'), ('3-5', '3-5 Yıl'), ('5-10', '5-10 Yıl'), ('10+', '10+ Yıl')], max_length=10, verbose_name='Deneyim Süresi')),
                ('cover_letter', models.TextField(verbose_name='Ön Yazı/Açıklama')),
                ('cv_file', models.FileField(help_text='PDF, DOC, DOCX formatında olmalıdır', upload_to=apps.careers.models.cv_upload_path, verbose_name='CV Dosyası')),
                ('status', models.CharField(choices=[('yeni', 'Yeni Başvuru'), ('inceleniyor', 'İnceleniyor'), ('mulakat', 'Mülakat Aşaması'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='yeni', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('notes', models.TextField(blank=True, help_text='İK değerlendirme notları', verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'İş Başvurusu',
                'verbose_name_plural': 'İş Başvuruları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='İş İlanı Başlığı')),
                ('department', models.CharField(choices=[('satis', 'Satış'), ('pazarlama', 'Pazarlama'), ('insan_kaynaklari', 'İnsan Kaynakları'), ('muhasebe', 'Muhasebe'), ('teknik', 'Teknik'), ('yonetim', 'Yönetim')], max_length=20, verbose_name='Departman')),
                ('employment_type', models.CharField(choices=[('tam_zamanli', 'Tam Zamanlı'), ('yari_zamanli', 'Yarı Zamanlı'), ('staj', 'Staj'), ('freelance', 'Freelance')], max_length=20, verbose_name='Çalışma Şekli')),
                ('location', models.CharField(default='İstanbul', max_length=100, verbose_name='Lokasyon')),
                ('description', models.TextField(verbose_name='İş Tanımı')),
                ('requirements', models.TextField(verbose_name='Aranan Özellikler')),
                ('qualifications', models.TextField(blank=True, verbose_name='Nitelikler')),
                ('benefits', models.TextField(blank=True, verbose_name='Sağladığımız Imkanlar')),
                ('salary_range', models.CharField(blank=True, max_length=50, verbose_name='Maaş Aralığı')),
                ('experience_required', models.CharField(blank=True, max_length=20, verbose_name='Gereken Deneyim')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Son Başvuru Tarihi')),
            ],
            options={
                'verbose_name': 'İş İlanı',
                'verbose_name_plural': 'İş İlanları',
                'ordering': ['-created_at'],
            },
        ),
    ]
