# Generated by Django 4.2.20 on 2025-06-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPosting',
        ),
    ]
