# Generated by Django 4.2.20 on 2025-04-12 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Departman Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('admin', 'Yönetici'), ('manager', 'Müdür'), ('consultant', 'Danışman'), ('secretary', 'Santral/Sekreter'), ('employee', 'Çalışan')], default='employee', max_length=20, verbose_name='Rol')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='İşe Başlama Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='İşten Ayrılma Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Çalışan Profili',
                'verbose_name_plural': 'Çalışan Profilleri',
                'ordering': ['-is_active', 'user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pozisyon Adı')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.department', verbose_name='Departman')),
            ],
            options={
                'verbose_name': 'Pozisyon',
                'verbose_name_plural': 'Pozisyonlar',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_customers', models.BooleanField(default=True, verbose_name='Müşteri Görüntüleme')),
                ('can_add_customers', models.BooleanField(default=False, verbose_name='Müşteri Ekleme')),
                ('can_edit_customers', models.BooleanField(default=False, verbose_name='Müşteri Düzenleme')),
                ('can_delete_customers', models.BooleanField(default=False, verbose_name='Müşteri Silme')),
                ('can_view_properties', models.BooleanField(default=True, verbose_name='Gayrimenkul Görüntüleme')),
                ('can_add_properties', models.BooleanField(default=False, verbose_name='Gayrimenkul Ekleme')),
                ('can_edit_properties', models.BooleanField(default=False, verbose_name='Gayrimenkul Düzenleme')),
                ('can_view_calendar', models.BooleanField(default=True, verbose_name='Takvim Görüntüleme')),
                ('can_create_events', models.BooleanField(default=True, verbose_name='Etkinlik Oluşturma')),
                ('can_edit_events', models.BooleanField(default=False, verbose_name='Etkinlik Düzenleme')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Raporları Görüntüleme')),
                ('can_manage_employees', models.BooleanField(default=False, verbose_name='Çalışan Yönetimi')),
                ('can_manage_settings', models.BooleanField(default=False, verbose_name='Sistem Ayarları')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='employees.employeeprofile', verbose_name='Çalışan')),
            ],
            options={
                'verbose_name': 'Özel İzin',
                'verbose_name_plural': 'Özel İzinler',
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.position', verbose_name='Pozisyon'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Eylem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('details', models.TextField(blank=True, verbose_name='Detaylar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Aktivite Kaydı',
                'verbose_name_plural': 'Aktivite Kayıtları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
