# Generated by Django 4.2.20 on 2025-04-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='start_date',
        ),
    ]
