# Generated by Django 4.2.20 on 2025-04-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeeprofile_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Pozisyon', 'verbose_name_plural': 'Pozisyonlar'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
