# Generated by Django 4.2.20 on 2025-06-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_position_options_remove_position_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='can_manage_employees',
        ),
        migrations.AddField(
            model_name='permission',
            name='can_access_admin_panel',
            field=models.BooleanField(default=False, verbose_name='Admin Panel Erişimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_access_hr_data',
            field=models.BooleanField(default=False, verbose_name='İK Verilerine Erişim'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_access_payroll',
            field=models.BooleanField(default=False, verbose_name='Bordro Erişimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_add_customer_notes',
            field=models.BooleanField(default=True, verbose_name='Müşteri Notu Ekleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_add_employees',
            field=models.BooleanField(default=False, verbose_name='Çalışan Ekleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_add_fsbo',
            field=models.BooleanField(default=False, verbose_name='FSBO Kayıt Ekleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_assign_customers',
            field=models.BooleanField(default=False, verbose_name='Müşteri Atama'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_assign_events',
            field=models.BooleanField(default=False, verbose_name='Etkinlik Atama'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_contact_fsbo_owners',
            field=models.BooleanField(default=True, verbose_name='FSBO Sahipleri ile İletişim'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_convert_fsbo_to_listing',
            field=models.BooleanField(default=False, verbose_name="FSBO'yu İlana Çevirme"),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_create_presentations',
            field=models.BooleanField(default=False, verbose_name='Sunum Oluşturma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_employees',
            field=models.BooleanField(default=False, verbose_name='Çalışan Silme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_events',
            field=models.BooleanField(default=False, verbose_name='Etkinlik Silme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_fsbo',
            field=models.BooleanField(default=False, verbose_name='FSBO Kayıt Silme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_presentations',
            field=models.BooleanField(default=False, verbose_name='Sunum Silme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_delete_properties',
            field=models.BooleanField(default=False, verbose_name='Gayrimenkul Silme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_download_presentations',
            field=models.BooleanField(default=True, verbose_name='Sunum İndirme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_customer_notes',
            field=models.BooleanField(default=False, verbose_name='Müşteri Notu Düzenleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_employees',
            field=models.BooleanField(default=False, verbose_name='Çalışan Düzenleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_fsbo',
            field=models.BooleanField(default=False, verbose_name='FSBO Kayıt Düzenleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_edit_presentations',
            field=models.BooleanField(default=False, verbose_name='Sunum Düzenleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_export_calendar',
            field=models.BooleanField(default=False, verbose_name='Takvim Dışa Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_export_customers',
            field=models.BooleanField(default=False, verbose_name='Müşteri Dışa Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_export_fsbo',
            field=models.BooleanField(default=False, verbose_name='FSBO Dışa Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_export_hr_reports',
            field=models.BooleanField(default=False, verbose_name='İK Raporu Dışa Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_export_properties',
            field=models.BooleanField(default=False, verbose_name='Gayrimenkul Dışa Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_export_reports',
            field=models.BooleanField(default=False, verbose_name='Rapor Dışa Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_feature_properties',
            field=models.BooleanField(default=False, verbose_name='Gayrimenkul Öne Çıkarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_generate_reports',
            field=models.BooleanField(default=False, verbose_name='Rapor Oluşturma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_hire_employees',
            field=models.BooleanField(default=False, verbose_name='Çalışan İşe Alma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_import_customers',
            field=models.BooleanField(default=False, verbose_name='Müşteri İçe Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_import_properties',
            field=models.BooleanField(default=False, verbose_name='Gayrimenkul İçe Aktarma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_interview_candidates',
            field=models.BooleanField(default=False, verbose_name='Aday Görüşme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_api_access',
            field=models.BooleanField(default=False, verbose_name='API Erişim Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_backups',
            field=models.BooleanField(default=False, verbose_name='Yedekleme Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_commissions',
            field=models.BooleanField(default=False, verbose_name='Komisyon Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_employee_permissions',
            field=models.BooleanField(default=False, verbose_name='Çalışan İzin Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_employee_roles',
            field=models.BooleanField(default=False, verbose_name='Çalışan Rol Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_event_types',
            field=models.BooleanField(default=False, verbose_name='Etkinlik Türü Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_fsbo_status',
            field=models.BooleanField(default=False, verbose_name='FSBO Durum Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_integrations',
            field=models.BooleanField(default=False, verbose_name='Entegrasyon Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_job_postings',
            field=models.BooleanField(default=False, verbose_name='İş İlanı Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_presentation_templates',
            field=models.BooleanField(default=False, verbose_name='Sunum Şablonu Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_property_photos',
            field=models.BooleanField(default=True, verbose_name='Gayrimenkul Fotoğraf Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_manage_recruitment_process',
            field=models.BooleanField(default=False, verbose_name='İşe Alım Süreci Yönetimi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_publish_properties',
            field=models.BooleanField(default=False, verbose_name='Gayrimenkul Yayınlama'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_send_invitations',
            field=models.BooleanField(default=True, verbose_name='Davetiye Gönderme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_set_pricing',
            field=models.BooleanField(default=False, verbose_name='Fiyatlandırma Yetkisi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_set_property_prices',
            field=models.BooleanField(default=False, verbose_name='Gayrimenkul Fiyat Belirleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_share_presentations',
            field=models.BooleanField(default=True, verbose_name='Sunum Paylaşma'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_track_presentation_views',
            field=models.BooleanField(default=False, verbose_name='Sunum Görüntüleme Takibi'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_activity_logs',
            field=models.BooleanField(default=False, verbose_name='Aktivite Kayıtları Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_all_customers',
            field=models.BooleanField(default=False, verbose_name='Tüm Müşterileri Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_all_events',
            field=models.BooleanField(default=False, verbose_name='Tüm Etkinlikleri Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_all_properties',
            field=models.BooleanField(default=False, verbose_name='Tüm Gayrimenkulleri Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_customer_notes',
            field=models.BooleanField(default=True, verbose_name='Müşteri Notları Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_employee_performance',
            field=models.BooleanField(default=False, verbose_name='Çalışan Performansı Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_employees',
            field=models.BooleanField(default=False, verbose_name='Çalışan Listesi Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_financial_data',
            field=models.BooleanField(default=False, verbose_name='Finansal Veri Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_fsbo',
            field=models.BooleanField(default=True, verbose_name='FSBO Listesi Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_job_applications',
            field=models.BooleanField(default=False, verbose_name='İş Başvuruları Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_presentations',
            field=models.BooleanField(default=True, verbose_name='Sunum Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_property_analytics',
            field=models.BooleanField(default=False, verbose_name='Gayrimenkul İstatistikleri'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_sales_reports',
            field=models.BooleanField(default=False, verbose_name='Satış Raporları Görüntüleme'),
        ),
        migrations.AddField(
            model_name='permission',
            name='can_view_system_logs',
            field=models.BooleanField(default=False, verbose_name='Sistem Logları Görüntüleme'),
        ),
    ]
