# Generated by Django 4.2.20 on 2025-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_update_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='extension_number',
            field=models.CharField(blank=True, help_text='Netgsm santral dahili numarası (örn: 101, 102, 103)', max_length=10, null=True, unique=True, verbose_name='Dahili Numara'),
        ),
    ]
