# Generated by Django 4.2.20 on 2026-06-28 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_add_yetki_fields'),
        ('customers', '0021_neighborhood_consultant2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0006_employeeprofile_extension_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Gorev Basligi')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('task_type', models.CharField(choices=[('neighborhood_visit', 'Mahalle Ziyareti'), ('photo_shoot', 'Fotograf Cekimi'), ('hang_banner', 'Branda Asma'), ('central_task', 'Santral Gorevi'), ('manual', 'Kendi Ekledigi')], default='manual', max_length=30, verbose_name='Gorev Tipi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandi'), ('overdue', 'Gecikmis')], default='pending', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Dusuk'), ('normal', 'Normal'), ('high', 'Yuksek'), ('urgent', 'Acil')], default='normal', max_length=10, verbose_name='Oncelik')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Son Tarih')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atayan')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='customers.neighborhood', verbose_name='Ilgili Mahalle')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='portfolio.property', verbose_name='Ilgili Portfoy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel')),
            ],
            options={
                'verbose_name': 'Personel Gorevi',
                'verbose_name_plural': 'Personel Gorevleri',
                'ordering': ['status', '-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Not Icerigi')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncelleme')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Kisisel Not',
                'verbose_name_plural': 'Kisisel Notlar',
                'ordering': ['is_completed', '-created_at'],
            },
        ),
    ]
