# Generated by Django 4.2.20 on 2026-07-01 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saha', '0007_parselkayit_portfoy_sayisi'),
        ('employees', '0007_usertask_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='parsel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='saha.parselkayit', verbose_name='Ilgili Parsel'),
        ),
    ]
