# Generated by Django 4.2.20 on 2025-04-11 21:29

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Rol')),
                ('priority', models.IntegerField(default=0, verbose_name='Öncelik (Yüksek değer daha önemli)')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_info', to='auth.group')),
            ],
            options={
                'verbose_name': 'Kullanıcı Rolü',
                'verbose_name_plural': 'Kullanıcı Rolleri',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-posta adresi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefon numarası')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='pozisyon')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='departman')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='profil fotoğrafı')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='son giriş IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'kullanıcı',
                'verbose_name_plural': 'kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
