# Generated by Django 4.2.20 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_id_alter_userrole_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Cep telefonu numarası (örn: 05321112233)', max_length=20, null=True, verbose_name='telefon numarası'),
        ),
    ]
